FROM node:18-alpine

# pnpm 설치
RUN npm install -g pnpm

WORKDIR /app

# package.json과 pnpm-lock.yaml을 복사
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

# 소스 코드 복사
COPY . .

EXPOSE 3000

CMD ["pnpm", "dev"] 