version: "3.8"

services:
  portfolio:
    # pnpm 기반 빌드/실행
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  nginx-ssl:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - portfolio
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./nginx.ssl.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/lib/letsencrypt:/var/lib/letsencrypt:ro
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email dldndldms@gmail.com --agree-tos --no-eff-email -d syncjin.com -d www.syncjin.com
    depends_on:
      - nginx-ssl

volumes:
  certbot-www:

networks:
  app-network:
    driver: bridge
