version: "3.8"

services:
  portfolio-dev:
    # pnpm 기반 빌드/실행
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  nginx-dev:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - portfolio-dev
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    driver: bridge
