version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    volumes:
      - ./public:/app/public
    depends_on:
      - certbot

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.ssl.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - nginx-logs:/var/log/nginx
    networks:
      - portfolio-network
    depends_on:
      - nextjs
      - certbot
    command: >
      sh -c "
        # 인증서가 없으면 HTTP 모드로 시작
        if [ ! -f /etc/letsencrypt/live/syncjin.com/fullchain.pem ]; then
          echo 'SSL 인증서가 없습니다. HTTP 모드로 시작합니다.'
          # HTTP 전용 설정으로 시작
          sed 's/listen 443 ssl http2;/# listen 443 ssl http2;/g; s/ssl_certificate/# ssl_certificate/g; s/ssl_certificate_key/# ssl_certificate_key/g' /etc/nginx/nginx.conf > /tmp/nginx-http.conf
          nginx -c /tmp/nginx-http.conf
        else
          echo 'SSL 인증서가 있습니다. HTTPS 모드로 시작합니다.'
          nginx -g 'daemon off;'
        fi
      "

  certbot:
    image: certbot/certbot
    container_name: portfolio-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email dldndldms@gmail.com --agree-tos --no-eff-email --staging -d syncjin.com

volumes:
  nginx-logs:

networks:
  portfolio-network:
    driver: bridge
