version: "3.8"

services:
  portfolio:
    # pnpm 기반 빌드/실행
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - portfolio
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
