version: "3.8"

services:
  portfolio:
    # pnpm 기반 빌드/실행
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
