version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-nextjs
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    volumes:
      - ./public:/app/public

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.ssl.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - nginx-logs:/var/log/nginx
    networks:
      - portfolio-network
    depends_on:
      - nextjs

volumes:
  nginx-logs:

networks:
  portfolio-network:
    driver: bridge
