name: Deploy to Vultr

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/syncjin/portfolio
            git pull origin main

            # SSL 설정 파일들이 있는지 확인하고 없으면 생성
            if [ ! -f "nginx.ssl.conf" ]; then
              echo "SSL 설정 파일이 없습니다. HTTP 모드로 실행합니다."
              docker compose down
              docker compose up -d --build
            else
              echo "SSL 설정 파일이 있습니다. HTTPS 모드로 실행합니다."
              docker compose down
              docker compose -f docker-compose.ssl.yml up -d --build
            fi
